### ISSUE TITLE
Bot not responding?

### ISSUE THREAD

**Issue by robustqueue** [logicplace/TumbleWeed-Discord#3]
Tumbleweed was offline for several days; when it came back online I tried to check on my followed lists and such, but it wouldn't respond despite entering the commands correctly. It seems to work now every couple of hours or so, where it can respond to one command, and then go back to being silent.

**Comment by logicplace** [comment]
Hmm. It was down for a bit so I ended up deploying it to a server so that won't happen so often, but it may have an effect like this. I don't have time to look into it right now, but I will when I can.

**Comment by logicplace** [comment]
Okay this should be fixed now. Sorry for the super long delay!! Merry Christmas!

**Comment by akiterus** [comment]
Is it down again? Because it has been offline for like 3 or 4 days now ):

**Comment by logicplace** [comment]
Sorry, I guess it was. Back up now.

**Comment by akiterus** [comment]
Now it's online but, it's not responding TT

**Comment by logicplace** [comment]
It's working for me, so I'm not sure.
