### ISSUE TITLE
Enter message:

### ISSUE THREAD

**Issue by akiterus** [logicplace/TumbleWeed-Discord#7]
Hi there, I'm sorry for bothering, but I'm completely new to this coding stuff (and github) and well, I tried to figure out how to run my own (just because I want it to have a different icon), the problem is that, **when I try to do the "node" step, I get the "Enter message:" message, and I'm just stuck there, is that supposed to show up? and if it does, what should I do next?** I entered commands of the bot and it responses but not in the server (the bot is still offline), just in the... coding box. So yeah, help would be really appreciated, and thank you.

**Comment by logicplace** [comment]
It shouldn't show up, no. Someone else had this issue but then change their issue to something else so I guess they figured it out.

@pzykotik what'd you end up doing?

**Comment by pzykotik** [comment]
In "settings.json",
Changed "sender": "console"
To "sender": "discord"

The bot would only go online at that point.

**Comment by akiterus** [comment]
Oh I see, I will try that out, thank you~

**Comment by akiterus** [comment]
It worked, thanks again!
