### ISSUE TITLE
Tags with more than one word

### ISSUE THREAD

**Issue by akiterus** [logicplace/TumbleWeed-Discord#9]
Hi, there are some tags with more than one word that I want to follow, but... it doesn't work. "Each tag set is separated by spaces and each tag within a tagset is separated by commas." but spaces also relay posts, right? And # is optional, so...

Doesn't that mean that... _if I do this: **tw!tumblr follow BlogName #something here,#blahblah** TumbleWeed will relay posts with "here"?_ even if I want to follow _#something here_ and _#blahblah_? 

I also tried using **tw!tumblr follow BlogName #something-here,#blahblah**, **tw!tumblr follow BlogName #something%20here,#blahblah** and **tw!tumblr follow BlogName #something+here,#blahblah** but it didn't work (I guess those aren't options in the bot code, heh). So, I'm just wondering if I'm doing something wrong, or if spaces operations are clashing. Thank you!

**Comment by logicplace** [comment]
> If a tag itself contains a space, you may use double quotes to quote the entire tagset.

So you would use "something here",#blahblah

**Comment by akiterus** [comment]
It works now, thank you!
